import { StyleSheet } from 'react-native';

export const theme = {
  colors: {
    primary: '#F9D1D1',      // Soft Pastel Pink
    secondary: '#FFE4E4',    // Lighter Pink (for loading/disabled)
    background: '#FFF5F5',   // Very Light Pink background
    card: '#FFFFFF',         // White cards
    text: '#5D4E4E',         // Soft Brownish-Grey
    danger: '#FF8080',       // Muted Coral for deletes
    border: '#E8B4B4',       // Dusty Rose
  }
};

export const globalStyles = StyleSheet.create({
  container: { 
    flex: 1, 
    backgroundColor: theme.colors.background, 
  },
  // NEW: Add this overlay style
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.7)', // Adjust 0.7 to change opacity (0-1)
    padding: 20,
    paddingTop: 60,
  },
  header: { 
    fontSize: 40, 
    fontWeight: 'bold', 
    textAlign: 'center', 
    marginBottom: 20,
    color: theme.colors.text
  },
  shelf: { 
    justifyContent: 'flex-start', 
    borderBottomWidth: 4, 
    borderBottomColor: theme.colors.border, 
    marginBottom: 20 
  },
  actionButton: {
    backgroundColor: theme.colors.primary,
    padding: 18,
    borderRadius: 20,
    alignItems: 'center',
    marginVertical: 15,
    borderWidth: 3,
    borderColor: theme.colors.border,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    elevation: 2,
  },
  box: { 
    width: '31%',                
    marginRight: '3.5%',         
    marginBottom: 15,           
    height: 100, 
    borderWidth: 2, 
    borderColor: theme.colors.border,
    justifyContent: 'center', 
    alignItems: 'center',
    position: 'relative',
    backgroundColor: theme.colors.card,
    borderRadius: 15,
  },
  text: { 
    fontWeight: 'bold',
    color: theme.colors.text
  },
  deleteButton: {
    position: 'absolute',
    top: 5,
    right: 5,
    backgroundColor: theme.colors.secondary,
    borderRadius: 10,
    width: 20,
    height: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  deleteText: { 
    fontSize: 10, 
    fontWeight: 'bold', 
    color: theme.colors.danger 
  },
  modalContent: { 
    flex: 1, 
    backgroundColor: theme.colors.background, 
    marginTop: 50 
  },
  scrollContainer: { 
    padding: 30, 
    paddingBottom: 60 
  },
  recipeTitle: { 
    fontSize: 32, 
    fontWeight: 'bold', 
    color: '#D48181', 
    marginBottom: 20 
  },
  sectionHeader: { 
    fontSize: 22, 
    fontWeight: 'bold', 
    marginTop: 20, 
    color: theme.colors.text 
  },
  bodyText: { 
    fontSize: 17, 
    lineHeight: 26, 
    color: theme.colors.text 
  },
  closeButton: { 
    marginTop: 40, 
    padding: 18, 
    backgroundColor: theme.colors.text, 
    borderRadius: 12, 
    alignItems: 'center' 
  },
  closeButtonText: { 
    color: '#fff', 
    fontWeight: 'bold' 
  },
  recipeOption: {
    backgroundColor: theme.colors.card,
    padding: 20,
    borderRadius: 15,
    marginBottom: 15,
    borderWidth: 2,
    borderColor: theme.colors.border,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    elevation: 1,
  },
  recipeOptionTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: theme.colors.text,
    flex: 1,
  },
  recipeOptionArrow: {
    fontSize: 24,
    color: '#D48181',
    fontWeight: 'bold',
  },
  backButton: {
    marginBottom: 15,
    padding: 12,
    backgroundColor: theme.colors.secondary,
    borderRadius: 10,
    alignSelf: 'flex-start',
  },
  backButtonText: {
    color: theme.colors.text,
    fontWeight: 'bold',
    fontSize: 16,
  },
  // AddButton styles
  addItemButton: { 
    backgroundColor: theme.colors.primary,
    borderColor: theme.colors.border,
    borderWidth: 3, 
    padding: 15, 
    alignItems: 'center', 
    marginTop: 10,
    borderRadius: 20,
  },
  addItemButtonText: { 
    color: theme.colors.text,
    fontSize: 20, 
    fontWeight: 'bold' 
  },
  // NewIngredient page styles
  pageContainer: {
    flex: 1,
    backgroundColor: theme.colors.background,
    padding: 20,
  },
  pageTitle: {
    paddingTop: 40,
    paddingBottom: 30,
    color: '#D48181',
    fontSize: 32,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  input: {
    height: 60,
    borderColor: theme.colors.border,
    borderWidth: 2,
    borderRadius: 15,
    marginBottom: 20,
    padding: 15,
    backgroundColor: theme.colors.card,
    fontSize: 18,
    color: theme.colors.text,
    fontWeight: '500',
  },
  inputLabel: {
    fontSize: 16,
    fontWeight: '600',
    color: theme.colors.text,
    marginBottom: 8,
    marginTop: 5,
  },
  saveButton: {
    backgroundColor: theme.colors.primary,
    paddingVertical: 18,
    paddingHorizontal: 30,
    borderRadius: 20,
    marginTop: 10,
    marginBottom: 15,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    elevation: 2,
  },
  cancelButton: {
    backgroundColor: theme.colors.secondary,
    paddingVertical: 18,
    paddingHorizontal: 30,
    borderRadius: 20,
    marginBottom: 30,
    alignItems: 'center',
    borderWidth: 2,
    borderColor: theme.colors.border,
  },
  notesInput: {
    height: 120,
    textAlignVertical: 'top',
  },
  buttonText: {
    color: theme.colors.text,
    fontSize: 18,
    fontWeight: 'bold',
  },
  // Improved Recipe Modal styles
  recipeModalContainer: {
    flex: 1,
    backgroundColor: theme.colors.background,
  },
  recipeScrollContent: {
    padding: 25,
    paddingTop: 60,
    paddingBottom: 40,
  },
  recipeHeader: {
    marginBottom: 25,
  },
  recipeBackButton: {
    alignSelf: 'flex-start',
    paddingVertical: 10,
    paddingHorizontal: 18,
    backgroundColor: theme.colors.secondary,
    borderRadius: 10,
    marginBottom: 20,
    borderWidth: 2,
    borderColor: theme.colors.border,
  },
  recipeBackButtonText: {
    color: theme.colors.text,
    fontSize: 16,
    fontWeight: '600',
  },
  selectedRecipeTitle: {
    fontSize: 36,
    fontWeight: 'bold',
    color: '#D48181',
    textAlign: 'center',
    marginBottom: 10,
    flexWrap: 'wrap',
    paddingHorizontal: 10,
  },
  recipeSection: {
    backgroundColor: theme.colors.card,
    borderRadius: 12,
    padding: 20,
    marginBottom: 20,
    borderWidth: 3,
    borderColor: theme.colors.border,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.08,
    elevation: 3,
  },
  recipeSectionTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#D48181',
    marginBottom: 15,
  },
  ingredientsList: {
    gap: 12,
  },
  ingredientItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
  },
  bulletPoint: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#D48181',
    marginTop: 8,
  },
  ingredientText: {
    flex: 1,
    fontSize: 17,
    color: theme.colors.text,
    lineHeight: 24,
  },
  instructionsText: {
    fontSize: 17,
    color: theme.colors.text,
    lineHeight: 26,
  },
  recipeCloseButton: {
    backgroundColor: '#D48181',
    paddingVertical: 18,
    paddingHorizontal: 40,
    borderRadius: 12,
    alignItems: 'center',
    marginTop: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    elevation: 4,
    borderWidth: 3,
    borderColor: '#C97070',
  },
  recipeCloseButtonText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: 'bold',
  },
  bookmarkButton: {
    backgroundColor: theme.colors.primary,
    paddingVertical: 18,
    paddingHorizontal: 40,
    borderRadius: 12,
    alignItems: 'center',
    marginTop: 10,
    marginBottom: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    elevation: 3,
    borderWidth: 3,
    borderColor: theme.colors.border,
  },
  bookmarkButtonText: {
    color: theme.colors.text,
    fontSize: 18,
    fontWeight: 'bold',
  },
  chooseRecipeTitle: {
    fontSize: 36,
    fontWeight: 'bold',
    color: '#D48181',
    textAlign: 'center',
    marginBottom: 8,
  },
  chooseRecipeSubtitle: {
    fontSize: 16,
    color: theme.colors.text,
    textAlign: 'center',
    marginBottom: 30,
    opacity: 0.7,
  },
  recipeOptionsContainer: {
    gap: 20,
    marginBottom: 10,
  },
  recipeBookCard: {
    height: 140,
    backgroundColor: theme.colors.card,
    borderRadius: 8,
    borderLeftWidth: 12,
    borderLeftColor: '#D48181',
    borderWidth: 3,
    borderColor: theme.colors.border,
    shadowColor: '#000',
    shadowOffset: { width: 4, height: 6 },
    shadowOpacity: 0.15,
    elevation: 5,
    overflow: 'hidden',
    flexDirection: 'row',
  },
  bookSpine: {
    width: 8,
    backgroundColor: '#C97070',
    borderRightWidth: 1,
    borderRightColor: '#B86060',
  },
  bookContent: {
    flex: 1,
    padding: 20,
    justifyContent: 'center',
  },
  recipeBookNumber: {
    fontSize: 14,
    fontWeight: '600',
    color: '#D48181',
    marginBottom: 8,
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  recipeBookTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: theme.colors.text,
    marginBottom: 10,
    flexShrink: 1,
  },
  tapToOpen: {
    fontSize: 14,
    color: theme.colors.text,
    opacity: 0.6,
    fontStyle: 'italic',
  },
  recipeOptionsCloseButton: {
    backgroundColor: theme.colors.secondary,
    paddingVertical: 18,
    paddingHorizontal: 40,
    borderRadius: 12,
    alignItems: 'center',
    marginTop: 20,
    borderWidth: 3,
    borderColor: theme.colors.border,
  },
  recipeOptionsCloseButtonText: {
    color: theme.colors.text,
    fontSize: 18,
    fontWeight: 'bold',
  },
  // Quantity display and modal styles
  quantityDisplayText: {
    fontSize: 13,
    color: '#D48181',
    fontWeight: '600',
    textAlign: 'center',
  },
  quantityBadge: {
    position: 'absolute',
    bottom: 5,
    right: 5,
    backgroundColor: '#D48181',
    borderRadius: 10,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  quantityText: {
    color: '#fff',
    fontSize: 11,
    fontWeight: 'bold',
  },
  quantityModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  quantityModalContent: {
    backgroundColor: theme.colors.card,
    borderRadius: 20,
    padding: 25,
    width: '80%',
    maxWidth: 300,
    borderWidth: 3,
    borderColor: theme.colors.border,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    elevation: 5,
  },
  quantityModalTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#D48181',
    textAlign: 'center',
    marginBottom: 8,
  },
  quantityModalSubtitle: {
    fontSize: 16,
    color: theme.colors.text,
    textAlign: 'center',
    marginBottom: 20,
    opacity: 0.7,
  },
  quantityInput: {
    height: 60,
    borderColor: theme.colors.border,
    borderWidth: 2,
    borderRadius: 12,
    marginBottom: 20,
    padding: 15,
    fontSize: 24,
    fontWeight: 'bold',
    color: theme.colors.text,
    textAlign: 'center',
    backgroundColor: theme.colors.background,
  },
  quantityModalButtons: {
    flexDirection: 'row',
    gap: 10,
  },
  quantityModalCancelButton: {
    flex: 1,
    backgroundColor: theme.colors.secondary,
    paddingVertical: 15,
    borderRadius: 12,
    alignItems: 'center',
    borderWidth: 2,
    borderColor: theme.colors.border,
  },
  quantityModalSaveButton: {
    flex: 1,
    backgroundColor: '#D48181',
    paddingVertical: 15,
    borderRadius: 12,
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#C97070',
  },
  unitLabel: {
    fontSize: 16,
    fontWeight: '600',
    color: theme.colors.text,
    marginBottom: 10,
  },
  unitScrollView: {
    maxHeight: 150,
    marginBottom: 20,
  },
  unitGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  unitButton: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    backgroundColor: theme.colors.secondary,
    borderWidth: 2,
    borderColor: theme.colors.border,
    minWidth: 85,
    alignItems: 'center',
  },
  unitButtonSelected: {
    backgroundColor: '#D48181',
    borderColor: '#C97070',
  },
  unitButtonText: {
    fontSize: 14,
    color: theme.colors.text,
    fontWeight: '500',
  },
  unitButtonTextSelected: {
    color: '#fff',
    fontWeight: 'bold',
  },
});